version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Running tests
          command: echo "Test done"

workflows:
  workflow-1:
    jobs:
      - build:
          pre-steps:
            - run:
                command: echo "install custom dependency"
              
          post-steps:
            - run:
                command: echo "upload artifact to s3"
